version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install pytest
            pipenv install -r app/requirements.txt
      - run:
          command: |
            mkdir test-results
            cd test-results
            mkdir pytest
      - run:
          command: |
            cd app
            pipenv run pytest
      - store_test_results:
          path: test-results